# Generated by Django 3.2.18 on 2023-06-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
